### ISSUE TITLE
rake shoppe:seed - NoMethodError: undefined method `default_image_file='

### ISSUE THREAD

**Issue by tr0ythex** [tryshoppe/shoppe#241]
Hello. I had the same problem like in this issue: https://github.com/tryshoppe/shoppe/issues/226
And as estelleccl adviced I ignored this missing command `rake shoppe:seed` at all.

But later I got new problem when I tried to open a certain product url (**like /product/yealink-t22p**). The error was `tryshoppe undefined method 'name' for nil:NilClass` and page wasn't rendered.

So I try to change shoppe gem in gemfile from version **1.1.0** to **1.0.9** and **1.0.8** and run `rake shoppe:seed`. It worked on version **1.0.8** and products were rendered ok with description and images.
Then I change gem version back to **1.1.0** and images disappeared.

As a result it all works on version **1.0.8** but it has different problems on latest version started with `rake shoppe:seed`. So I decided to left version **1.0.8** in my gemfile for now and ask for some help here. Thanks in advance.

**P.S**. Sorry for some grammar mistakes. English is not my native language. If you don't understand something I wrote, please ask me :)

**P.P.S**. I use cloude IDE c9.io for development
Rails version is **4.2.3**
Ruby version is **ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]**

**Comment by kumar91gopi** [comment]
i am facing the same issue. i upgraded my Rails version to 4.2.1 and Ruby 2.2.1 but still the rake is aborted.

kumar91gopi@shoppe:~/workspace/wardrobe $ rake shoppe:seed
rake aborted!
NoMethodError: undefined method default_image_file=' for #<Shoppe::Product:0x000000076a2988> /usr/local/rvm/gems/ruby-2.2.1/gems/activemodel-4.2.1/lib/active_model/attribute_methods.rb:433:inmethod_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/shoppe-1.1.0/db/seeds.rb:35:in <top (required)>' /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:inrequire'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in block in require' /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:inload_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in require' /usr/local/rvm/gems/ruby-2.2.1/gems/shoppe-1.1.0/lib/tasks/shoppe.rake:5:inblock (2 levels) in '
Tasks: TOP => shoppe:seed
(See full trace by running task with --trace)

**Comment by tr0ythex** [comment]
I think this issue also broke the demo site

**Comment by tr0ythex** [comment]
@deanperry thank you
