### PR TITLE
add missing method to product.rb, fixes #241.

### LINKED ISSUE #241: rake shoppe:seed - NoMethodError: undefined method `default_image_file='
Hello. I had the same problem like in this issue: https://github.com/tryshoppe/shoppe/issues/226
And as estelleccl adviced I ignored this missing command `rake shoppe:seed` at all.

But later I got new problem when I tried to open a certain product url (**like /product/yealink-t22p**). The error was `tryshoppe undefined method 'name' for nil:NilClass` and page wasn't rendered.

So I try to change shoppe gem in gemfile from version **1.1.0** to **1.0.9** and **1.0.8** and run `rake shoppe:seed`. It worked on version **1.0.8** and products were rendered ok with description and images.
Then I change gem version back to **1.1.0** and images disappeared.

As a result it all works on version **1.0.8** but it has different problems on latest version started with `rake shoppe:seed`. So I decided to left version **1.0.8** in my gemfile for now and ask for some help here. Thanks in advance.

**P.S**. Sorry for some grammar mistakes. English is not my native language. If you don't understand something I wrote, please ask me :)

**P.P.S**. I use cloude IDE c9.io for development
Rails version is **4.2.3**
Ruby version is **ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]**

### PR DESCRIPTION
**Pull request by hilquias**

### CODE REVIEW

**Comment by quocnv** [comment]
I see document not work, error action buy.

undefined method `orderable?' for nil:NilClass

Please check @product is nil

def buy
    @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
    current_order.order_items.add_item(@product, 1)
    redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
  end

**Comment by deanperry** [comment]
You'll need to change `Shoppe::Product.root.find_by_permalink` to `Shoppe::Product.root.find_by_permalink!` - notice the !

**Comment by quocnv** [comment]
Hi deanperry

Shoppe::Product.root.find_by_permalink!  find pdouct is nil. while record exists my db

product is nil => current_order.order_items.add_item(@product, 1) rase error undefined method `orderable?' for nil:NilClass

Thanks you

**Comment by deanperry** [comment]
:+1: Thanks
